default: &default
  adapter: postgresql
  host: localhost
  pool: 5
  timeout: 5000
  username: postgres
  password: myPassword

development:
  <<: *default
  database: e_comerce_api_development

test:
  <<: *default
  database: e_comerce_api_test

production:
  <<: *default
  database: e_comerce_api_production
